### ISSUE TITLE
Problems with TestScript1_SingleGustPlots.py and TestScript3_MultGustsSurfPressure.py

### ISSUE THREAD

**Issue by ccyw19384** [fchirono/amiet_tools#1] opened 2020-08-24 09:04 UTC
Hello everyone, I tested the amiet_tool and found some errors. The debug of "TestScript1_SingleGustPlots.py" shows "divided by zero" and the debug of "TestScript3_MultGustsSurfPressure.py" shows "lack of array_tool". Any tip is helpful.

**Comment by fchirono** [comment] 2020-08-24 21:49
In _TestScript1_SingleGustPlots.py_, the "divided by zero" warning message appears in line 132, when calculating the magnitude of the airfoil surface pressure jump in decibels. The pressure is exactly zero at the trailing edge due to the Kutta conditon, leading to `np.log10(0) = -np.inf`, which is where Python throws the "divided by zero" warning. See, for example, [this StackOverflow link](https://stackoverflow.com/questions/36229340/divide-by-zero-encountered-in-log-when-not-dividing-by-zero/36229376). This is normal and expected behavior, and you can safely ignore it.

In _TestScript3_MultGustsSurfPressure.py_, I thought I had removed the `array_tools` dependency from the test script but I clearly forgot about it, sorry! `array_tools` is a separate (unpublished) package that contains a function to calculate the wavenumber transform (or Spatial Fourier Transform) of the surface pressure. See Figure 4 in [this paper](https://doi.org/10.2514/6.2018-3135) to have an idea of what I'm talking about. As this calculation and associated figure were not meant to be published in this package, I'll update the test script to remove this dependency and the related figure (line 208 onwards) and close the issue.

This is a fairly specialized type of analysis and probably won't be of interest to most users, so for now I'd rather to keep it out of the `amiet_tools` package. If you are interested in generating the wavenumber transform plot, let me know and I'll think of a way to give you the code.

**Closed as completed by fchirono** 2020-08-24 21:49 UTC

**Comment by ccyw19384** [comment] 2020-08-25 01:59
> and
Thank you for your quick and detailed reply. Your open source code is very helpful to those of us who are not familiar with this field. I'll learn the theory first, and then email you if necessary.
